# Generated by Django 4.1.7 on 2023-04-13 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reseller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.TextField(db_column="reseller_company_name", max_length=50),
                ),
                ("reg_id", models.TextField(db_column="company_reg_id", max_length=50)),
                (
                    "account_number",
                    models.TextField(db_column="bank_account_number", max_length=50),
                ),
                (
                    "ifsc_code",
                    models.TextField(db_column="bank_ifsc_code", max_length=50),
                ),
                (
                    "branch_bank",
                    models.TextField(db_column="bank_branch_name", max_length=50),
                ),
                (
                    "address",
                    models.TextField(db_column="company_address", max_length=50),
                ),
                (
                    "country",
                    models.TextField(db_column="company_country", max_length=50),
                ),
                ("mobile", models.TextField(db_column="mobile_number", max_length=50)),
                ("email", models.TextField(db_column="company_email", max_length=50)),
                ("password", models.TextField(db_column="pass_word", max_length=50)),
                ("otp", models.TextField(db_column="company_otp", max_length=50)),
                (
                    "status",
                    models.TextField(
                        db_column="company_status", default="inactive", max_length=50
                    ),
                ),
                (
                    "request_date",
                    models.DateField(
                        db_column="request_date", default=datetime.datetime.now
                    ),
                ),
            ],
            options={
                "db_table": "reseller",
            },
        ),
    ]
