# Generated by Django 4.1.7 on 2023-04-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reseller", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reseller",
            name="user_id",
            field=models.IntegerField(db_column="login_id", max_length=50, null=True),
        ),
    ]
