# Generated by Django 4.1.7 on 2023-05-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reseller", "0003_alter_reseller_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Add_product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(db_column="pro_title", max_length=50)),
                (
                    "pro_id",
                    models.TextField(db_column="registerd_pro_id", max_length=50),
                ),
                (
                    "discription",
                    models.TextField(db_column="pro_discription", max_length=100),
                ),
                (
                    "pro_picture",
                    models.TextField(db_column="pro_pictures", max_length=50),
                ),
                ("price", models.IntegerField(db_column="pro_price", max_length=50)),
                (
                    "quantity",
                    models.IntegerField(db_column="pro_quantity", max_length=50),
                ),
                ("weight", models.IntegerField(db_column="pro_weight", max_length=50)),
                (
                    "weight_unit",
                    models.TextField(db_column="pro_weight_unit", max_length=50),
                ),
                ("catagory", models.TextField(db_column="pro_catagory", max_length=50)),
                (
                    "sub_catagory",
                    models.TextField(db_column="pro_sub_catagory", max_length=50),
                ),
                ("brand", models.TextField(db_column="pro_brand", max_length=50)),
                ("Status", models.TextField(db_column="pro_status", max_length=50)),
            ],
            options={
                "db_table": "add_product",
            },
        ),
    ]
