# Generated by Django 4.1.7 on 2023-05-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reseller", "0004_add_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="add_product",
            name="price",
            field=models.IntegerField(db_column="pro_price"),
        ),
        migrations.AlterField(
            model_name="add_product",
            name="quantity",
            field=models.IntegerField(db_column="pro_quantity"),
        ),
        migrations.AlterField(
            model_name="add_product",
            name="weight",
            field=models.IntegerField(db_column="pro_weight"),
        ),
    ]
