# Generated by Django 4.1.7 on 2023-03-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField(db_column="f_name", max_length=30)),
                ("last_name", models.TextField(db_column="l_name", max_length=30)),
                ("gender", models.CharField(db_column="gender", max_length=6)),
                ("dateofbirth", models.DateField(db_column="date_of_birth")),
                ("address", models.TextField(db_column="address", max_length=100)),
                ("country", models.TextField(db_column="country", max_length=20)),
                ("mobilenumber", models.TextField(db_column="mob_num", max_length=20)),
                ("email", models.TextField(db_column="email", max_length=20)),
                ("password", models.TextField(db_column="password", max_length=15)),
                ("otp", models.CharField(db_column="otp", max_length=100)),
                (
                    "status",
                    models.TextField(db_column="status", default="", max_length=20),
                ),
            ],
            options={
                "db_table": "customer",
            },
        ),
    ]
